### ISSUE TITLE
Add support for ivy

### ISSUE THREAD

**Issue by pietie** [lon-yang/ngx-markdown-editor#48]
Using ng version 9.0.0-next.6 I get the error below.
If I turn ivy off in tsconfig the error goes away and md-editor renders and works fine.

core.js:3759 ERROR NullInjectorError: R3InjectorError(AppModule)[Renderer -> Renderer -> Renderer]: 
  NullInjectorError: No provider for Renderer!
    at NullInjector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.NullInjector.get (http://localhost:4201/vendor.js:37559:27)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.get (http://localhost:4201/vendor.js:48401:33)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.get (http://localhost:4201/vendor.js:48401:33)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.get (http://localhost:4201/vendor.js:48401:33)
    at NgModuleRef$1.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.NgModuleRef$1.get (http://localhost:4201/vendor.js:60096:33)
    at Object.get (http://localhost:4201/vendor.js:58530:35)
    at getOrCreateInjectable (http://localhost:4201/vendor.js:40339:39)
    at ɵɵdirectiveInject (http://localhost:4201/vendor.js:51228:12)
    at NodeInjectorFactory.MarkdownEditorComponent_Factory [as factory] (ng:///MarkdownEditorComponent/ngFactory.js:6:44)
    at getNodeInjectable (http://localhost:4201/vendor.js:40448:44)

**Comment by sakenk** [comment]
Hi,

I have to put
value="{item.attribute}"
How can i do it is it possible to do it?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lon-yang** [comment]
@pietie . I will check this later.

@sakenk . I'm sorry, I do not quite understand you. Or create an new issue for this.

**Comment by sakenk** [comment]
i want to add property binding with value attribute like so [value]="" is it possible?

**Comment by lon-yang** [comment]
@sakenk  This component has not `value` input.

**Comment by lon-yang** [comment]
@pietie Please upgrade to `2.2.0`.
